[package]
name = "counter-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
essential-app-utils = "0.6.0"
essential-hash = "0.9.0"
essential-rest-client = "0.6.0"
essential-types = "0.7.0"
pint-abi = "0.11.0"
tokio = { version = "1.42.0", features = ["full"] }

[dev-dependencies]
essential-app-utils = { version = "0.6.0", features = ["test-utils"] }
essential-builder = "0.11.0"
essential-builder-db = "0.6.0"
essential-node = "0.9.0"
serde_json = "1.0.133"
